### ISSUE TITLE
Extract food values for products crawled from Goodsmatrix

### ISSUE THREAD

**Issue by KMax** [ailabitmo/foodpedia#2]
Use the following data properties to represent the food values:
 * fat - `food:fatPer100gAsDouble`
 * proteins - `food:proteinsPer100gAsDouble`
 * carbohydrates - `food:carbohydratesPer100gAsDouble`
 * energy (aka calories) - `food:energyPer100gAsDouble`

Prefix `food` refers to `http://purl.org/foodontology#`

**Comment by chistyakov** [comment]
Ready for test on testing server

**Comment by chistyakov** [comment]
deployed to production:
http://foodpedia.tk/page/1701225500007

**Comment by KMax** [comment]
Awesome! Thanks @chistyakov :+1:

**Comment by chistyakov** [comment]
:)
You know how to motivate people with recognition. Has anyone told you that the world is losing great Project Manager in your face :)
