### ISSUE TITLE
Create and publish VoID description

### ISSUE THREAD

**Issue by KMax** [ailabitmo/foodpedia#26]
VoID is a vocabulary for expressing metadata about RDF datasets. [Here](http://www.w3.org/TR/void/) is a document describing the vocabulary and steps to publish the description.

**Comment by KMax** [comment]
@mignolowa I just committed a cleaned up and enhanced version of void.ttl. I removed some unfinished pieces and refactored the file according to Turtle format.

Later we will update the statistics, but for now I think we can close this issue.

Thanks @mignolowa! Good job!

**Comment by KMax** [comment]
Oops, I've forgot that we need to publish `void.ttl` now :) I'll do it.

**Comment by mignolowa** [comment]
Thank you Maxim!

**Comment by KMax** [comment]
Done. Available at http://foodpedia.tk/void.ttl or http://foodpedia.tk with `Accept: text/turtle` header.
