### ISSUE TITLE
Links 'As Turtle' and 'As RDF/XML' don't work

### ISSUE THREAD

**Issue by KMax** [ailabitmo/foodpedia#3]
I.e. go to http://foodpedia.tk/page/resource/6416597839321 and press one of the links.

**Comment by chistyakov** [comment]
fixed:
http://foodpedia.tk/page/6416597839321

BTW, by default pubby provides few other links:
![image](https://cloud.githubusercontent.com/assets/2177714/6098006/f26ad6c2-afe1-11e4-9f18-958455807237.png)

I [explicitly replaced](https://github.com/ailabitmo/foodpedia/blob/master/foodpedia-pubby/pubby-builder/Dockerfile#L14) footer.html to be consistent with first deployed version of foodpeida.tk.

**Comment by KMax** [comment]
I'm not sure that these links work, because Disco, Tabulator and OpenLink Browser can be unmaintained :( So I'm okay to hide them.
