### ISSUE TITLE
Link E-additives to corresponding resources in DBpedia

### ISSUE THREAD

**Issue by KMax** [ailabitmo/foodpedia#30]
In [eadd.ttl](https://github.com/ailabitmo/foodpedia/blob/master/upload/eadd.ttl) we have a list of E-additives which we have in FOODpedia. The goal is to find for each E-additive a corresponding resource in DBpedia and link them with `skos:exactMatch` property.

In example:
```
@prefix foodpedia: <http://foodpedia.tk/resource/> .
@prefix dbpedia: <http://dbpedia.org/resource/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .

foodpedia:E100 skos:exactMatch <http://dbpedia.org/resource/Curcumin>
```

**Comment by chistyakov** [comment]
It also make sense to review this dataset. At least, the prefix name ns1 should be renamed to something meaningful.
This dataset was created by CONSTRUCT request to sparql endpoint before our first server died.

**Comment by m-lapaev** [comment]
Btw, we also have a parsed dataset of E-additives from добавкам.net which could used as a source of description as well. At least it contains alternative names in Russian and Ukrainian.

**Comment by mignolowa** [comment]
I`ve done it.

**Comment by chistyakov** [comment]
:thumbsup:

**Comment by KMax** [comment]
Your first issue! :) Thanks @mignolowa! I know, it wasn't easy!
