### ISSUE TITLE
Extract E-additives from Goodsmatrix

### ISSUE THREAD

**Issue by KMax** [ailabitmo/foodpedia#4]
Some food products have contains E-additives in their ingredient lists that could be easily extracted, i.e. http://foodpedia.tk/page/resource/4005500027430

Depends on #7.

**Comment by chistyakov** [comment]
Ready for test on testing server:
http://109.234.34.200/page/1701225500007

**Comment by chistyakov** [comment]
Known bugs (#18, #19) are fixed. Latest dump deployed to production

**Comment by KMax** [comment]
Thanks @chistyakov! Great job!
