### ISSUE TITLE
Rewrite foodpedia-parser in Python

### ISSUE THREAD

**Issue by KMax** [ailabitmo/foodpedia#5]

**Comment by chistyakov** [comment]
Parser for goodsmatrix.ru was redesigned in Python. It still could be improved, but at least it covers functionality provided by first version of parser.

All enhancements/bugs should be handled separately.

Post processing was moved to [special pipelines](https://github.com/ailabitmo/foodpedia/blob/master/foodpedia-parser-v2/goodsmatrix/pipelines/postprocessors.py), configurable via settings.
